version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always

  go-matching-engine:
    build: ./go
    ports:
      - "8081:8081"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  java-matching-engine:
    build: ./java
    ports:
      - "8082:8082"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  node-matching-engine:
    build: ./node
    ports:
      - "8083:8083"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  rust-matching-engine:
    build: ./rust
    ports:
      - "8084:8084"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  cpp-matching-engine:
    build: ./cpp
    ports:
      - "8085:8085"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
