[package]
name = "matching_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
redis = "0.25.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36.0", features = ["full"] }
